spring:
  application:
    name: order-event-driven-consumer-service
  cloud:
    stream:
      default-binder: kafka
      kafka:
        binder:
          brokers: localhost:9092
      bindings:
        event-consumer:
          destination: order_topic
          contentType: application/json
server:
  port : 9002
management:
  endpoint:
    health:
      enabled: true
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
    jmx:
      exposure:
        include: '*'