spring:
  application:
    name: spring-gateway-demo
  redis:
    host: localhost
    port: 6379    
  cloud:
    gateway:
      routes:
      - id: catalogues_route
        uri: http://localhost:8010
        predicates:
        - Path=/catalogue
        - Weight=group1, 6
        filters:
        - name: RequestRateLimiter
          args:
            redis-rate-limiter.replenishRate: 2
            redis-rate-limiter.burstCapacity: 4
      - id: customers_route
        uri: http://localhost:8011
        predicates:
        - Path=/customers

#Actuator health check    
management:
  endpoints:
    web:
      exposure:
        include: "*"